name: Generate Alerts JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Generate Dogecoin Shibe Alerts JSON
      run: |
        node <<EOF
        const fs = require('fs');
        const path = require('path');

        const basePath = './alerts';
        const alerts = [];

        try {
          const types = fs.readdirSync(basePath).filter(type => {
            const typePath = path.join(basePath, type);
            return fs.statSync(typePath).isDirectory();
          });

          console.log('Types found:', types); // Debug

          types.forEach(type => {
            const typePath = path.join(basePath, type);
            const statuses = fs.readdirSync(typePath).filter(status => {
              const statusPath = path.join(typePath, status);
              return fs.statSync(statusPath).isDirectory();
            });

            console.log('Statuses found for type', type, ':', statuses); // Debug

            statuses.forEach(status => {
              const statusPath = path.join(typePath, status);
              const files = fs.readdirSync(statusPath).filter(file => file.match(/^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}\.txt$/));

              console.log('Files found for status', status, ':', files); // Debug

              files.forEach(file => {
                const filePath = path.join(statusPath, file);
                const content = fs.readFileSync(filePath, 'utf-8');
                const [url, title] = content.split('\n').map(line => line.trim());

                if (!url || !title) {
                  console.error(`Invalid file structure in ${filePath}.`);
                  return;
                }

                // Extract the datetime from the filename with correct format
                const fileDateTime = file
                  .replace('.txt', '').split('_').map((part, index) => {
                    if (index === 1) {
                      return part.replace(/-/g, ':');
                    }
                    return part;
                  }).join('T');

                alerts.push({
                  id: alerts.length + 1,
                  type: type,
                  status: status,
                  title: title,
                  url: url,
                  datetime: fileDateTime // Use the filename's date and time
                });
              });
            });
          });

          // Write the alerts JSON with full path
          const outputPath = path.join(__dirname, 'db.json');
          fs.writeFileSync(outputPath, JSON.stringify(alerts, null, 2));
          console.log('Generated db.json successfully at', outputPath);

        } catch (error) {
          console.error('Error generating alerts JSON:', error);
          process.exit(1); // Exit with error
        }
        EOF

    - name: Commit and Push Dogecoin Shibe Alerts to db.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add db.json
        git commit -m "Update db.json"
        git push
